# Copied and adapted from Sodium CI

name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: adopt
    - name: Cache/Uncache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/loom-cache
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build artifacts
      run: ./gradlew build
    - name: Extract current branch name
      shell: bash
      # bash pattern expansion to grab branch name without slashes
      run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
      id: ref
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openalmc-artifacts-${{ steps.ref.outputs.branch }}
        # Filter built files to disregard -sources and -dev, and leave only the minecraft-compatible jars.
        # This also filters out unstable versions, and only builds for tagged versions.
        path: build/libs/*[0-9].jar
